     const dscau = [
    "Chúc mừng 8/3 em yêu! Cảm ơn em đã bước vào cuộc đời anh và mang đến những ngày tháng tràn đầy yêu thương và hạnh phúc. Chúc em luôn xinh đẹp, dịu dàng và giữ mãi nụ cười rạng rỡ trên môi. Anh mong sẽ luôn được ở bên, che chở và cùng em viết tiếp câu chuyện tình yêu thật dài phía trước. ❤️",
    "Nhân ngày Quốc tế Phụ nữ 8/3, anh chúc em luôn vui vẻ, mạnh mẽ và tự tin theo đuổi ước mơ của mình. Em không chỉ là người anh yêu mà còn là nguồn động lực giúp anh cố gắng mỗi ngày. Mong rằng tình yêu của chúng ta sẽ luôn ấm áp, bền lâu và tràn ngập những khoảnh khắc ngọt ngào. 💐",
    "Nhân ngày Quốc tế Phụ nữ 8/3 này anh muốn gửi đến em tất cả sự yêu thương và trân trọng từ trái tim mình. Cảm ơn em vì đã luôn quan tâm, thấu hiểu và đồng hành cùng anh trong mọi khoảnh khắc. Chúc em luôn hạnh phúc, bình an và tỏa sáng theo cách riêng, vì với anh em luôn là điều tuyệt vời nhất. 🌷",
    "Chúc mừng Ngày Quốc tế Phụ nữ 8/3! Chúc bạn luôn xinh đẹp, tự tin và mạnh mẽ theo đuổi ước mơ của mình. Mong rằng mỗi ngày trôi qua đều tràn đầy niềm vui, bình an và yêu thương. Cảm ơn bạn vì những điều dịu dàng và tốt đẹp đã mang đến cho mọi người xung quanh.",
	"Nhân ngày 8/3, chúc bạn luôn rạng rỡ, hạnh phúc và tràn đầy năng lượng tích cực. Mong rằng mọi dự định trong cuộc sống và công việc đều thuận lợi, thành công. Hãy luôn giữ nụ cười trên môi, sự ấm áp trong tim và tận hưởng những điều tuyệt vời mà cuộc sống mang lại.",
	"Chúc bạn một ngày Quốc tế Phụ nữ thật ý nghĩa và ngập tràn yêu thương. Mong rằng bạn luôn được trân trọng, quan tâm và nâng niu không chỉ hôm nay mà trong mọi khoảnh khắc của cuộc sống. Chúc bạn nhiều sức khỏe, niềm vui và luôn tỏa sáng theo cách riêng của mình",
	"Ngày 8/3 xin gửi đến bạn những lời chúc tốt đẹp nhất. Chúc bạn luôn mạnh mẽ, tự tin và thành công trên con đường mình chọn. Mong rằng cuộc sống sẽ luôn dịu dàng với bạn, mang đến thật nhiều niềm vui, may mắn và những khoảnh khắc hạnh phúc bên người thân yêu. 🌷💐",
	"Chúc mừng 8/3 vợ yêu của anh! Cảm ơn em đã luôn bên anh, chăm lo gia đình và mang đến thật nhiều yêu thương cho tổ ấm nhỏ của chúng ta. Chúc em luôn xinh đẹp, vui vẻ và hạnh phúc mỗi ngày. Với anh, em mãi là điều tuyệt vời và quý giá nhất trong cuộc đời này. ❤️",
	"Nhân ngày Quốc tế Phụ nữ 8/3, anh chúc vợ yêu luôn khỏe mạnh, rạng rỡ và tràn đầy năng lượng. Cảm ơn em vì sự hy sinh thầm lặng và những yêu thương em dành cho anh và gia đình. Anh mong sẽ luôn được nắm tay em, cùng nhau đi hết chặng đường dài phía trước. 💐",
	"8/3 này, anh chỉ muốn nói rằng anh thật may mắn khi có em làm vợ. Cảm ơn em vì đã luôn thấu hiểu, sẻ chia và đồng hành cùng anh trong mọi vui buồn. Chúc em luôn được yêu thương, trân trọng và sống thật hạnh phúc, vì em xứng đáng với tất cả những điều tốt đẹp nhất. 🌷",
	"Nhân ngày Quốc tế Phụ nữ 8/3, con chúc mẹ luôn mạnh khỏe, vui vẻ và sống thật lâu bên gia đình. Cảm ơn mẹ đã hy sinh, chăm sóc và dành trọn tình yêu thương cho chúng con suốt bao năm qua. Với con, mẹ luôn là người phụ nữ tuyệt vời nhất và là điểm tựa bình yên trong cuộc đời. ❤️",
	"Chúc mừng 8/3 mẹ yêu! Con biết ơn mẹ vì những vất vả thầm lặng và sự bao dung vô điều kiện mà mẹ dành cho gia đình. Mong mẹ luôn an yên, hạnh phúc và giữ mãi nụ cười hiền hậu. Con sẽ cố gắng thật nhiều để mẹ luôn tự hào và có cuộc sống nhẹ nhàng hơn mỗi ngày. 💐",
	"Ngày 8/3, con chỉ muốn nói rằng con yêu mẹ rất nhiều. Cảm ơn mẹ đã luôn che chở, dạy dỗ và đồng hành cùng con qua mọi chặng đường. Chúc mẹ luôn dồi dào sức khỏe, bình an và hạnh phúc. Mong rằng mỗi ngày trôi qua đều mang đến cho mẹ thật nhiều niềm vui và yêu thương. 🌷"
	
	];